# Generated by Django 6.0.5 on 2026-05-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, null=True, verbose_name='Marca del Auto')),
                ('model', models.CharField(max_length=20, verbose_name='Modelo')),
                ('photo', models.ImageField(blank=True, upload_to='car/', verbose_name='Foto del Auto')),
                ('preview', models.TextField(verbose_name='Previsualizacion Auto')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('photo_interior', models.ImageField(blank=True, upload_to='interior_car/', verbose_name='Fotos de Interior del Auto')),
                ('tires', models.CharField(max_length=20, verbose_name='Dimensiones del Auto')),
                ('max_speed', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Peso')),
                ('tire', models.CharField(max_length=30, verbose_name='Litros de Consumo')),
                ('external_color', models.CharField(max_length=20, null=True, verbose_name='Color exterior')),
                ('internal_color', models.CharField(max_length=20, null=True, verbose_name='Color interior')),
                ('stock', models.IntegerField(verbose_name='Unidades disponibles')),
                ('availability', models.CharField(max_length=20, verbose_name='Disponibilidad del Auto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio del Auto')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
            },
        ),
    ]
